github: @FabianaCampanari
['https://github.com/FabianaCampanari',
'https://github.com/FabianaCampanari/Average-Calculator']
open_collective: @FabianaCampanari
['https://opencollective.com/fabianacampanari',
'https://opencollective.com/fabianacampanari/projects/average-calculator']
